global:
  scrape_interval: 45s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 45s
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'docker'
    scrape_interval: 45s
    static_configs:
      - targets: ['cadvisor:8080']


  - job_name: 'node'
    scrape_interval: 45s
    static_configs:
      - targets: ['node-exporter:9100']
